/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MedicineLabelResult = IDL.Record({
  'medicationName' : IDL.Text,
  'hasEmergencyAlert' : IDL.Bool,
  'emergencyAlertText' : IDL.Text,
  'warnings' : IDL.Text,
  'howToTake' : IDL.Text,
  'storageInstructions' : IDL.Text,
  'sideEffects' : IDL.Text,
  'purpose' : IDL.Text,
  'dosageInstructions' : IDL.Text,
});
export const ProcessLabelResult = IDL.Variant({
  'ok' : MedicineLabelResult,
  'err' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'processLabel' : IDL.Func([IDL.Text, IDL.Text], [ProcessLabelResult], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MedicineLabelResult = IDL.Record({
    'medicationName' : IDL.Text,
    'hasEmergencyAlert' : IDL.Bool,
    'emergencyAlertText' : IDL.Text,
    'warnings' : IDL.Text,
    'howToTake' : IDL.Text,
    'storageInstructions' : IDL.Text,
    'sideEffects' : IDL.Text,
    'purpose' : IDL.Text,
    'dosageInstructions' : IDL.Text,
  });
  const ProcessLabelResult = IDL.Variant({
    'ok' : MedicineLabelResult,
    'err' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'processLabel' : IDL.Func([IDL.Text, IDL.Text], [ProcessLabelResult], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };